"""autogenerated by genpy from vn_200_imu/vn_200_gps_soln.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class vn_200_gps_soln(genpy.Message):
  _md5sum = "7d5e768e2131af394154c512a558f76a"
  _type = "vn_200_imu/vn_200_gps_soln"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

float64 latitude
float64 longitude
float64 altitude

int32 num_satellites

# gives the velocities in north-east-down directions
# x is north velocity
# y is east  velocity
# z is down  velocity
geometry_msgs/Vector3 ned_velocities

# gives the acceleration in north-east-down directions
# x is north acceleration
# y is east  acceleration
# z is down  acceleration
geometry_msgs/Vector3 ned_acceleration

# the speed accuracy estimate in meters/sec
float64 speed_accuracy_estimate

# error checking information
bool error_present
string error_string

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['header','latitude','longitude','altitude','num_satellites','ned_velocities','ned_acceleration','speed_accuracy_estimate','error_present','error_string']
  _slot_types = ['std_msgs/Header','float64','float64','float64','int32','geometry_msgs/Vector3','geometry_msgs/Vector3','float64','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,latitude,longitude,altitude,num_satellites,ned_velocities,ned_acceleration,speed_accuracy_estimate,error_present,error_string

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(vn_200_gps_soln, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.altitude is None:
        self.altitude = 0.
      if self.num_satellites is None:
        self.num_satellites = 0
      if self.ned_velocities is None:
        self.ned_velocities = geometry_msgs.msg.Vector3()
      if self.ned_acceleration is None:
        self.ned_acceleration = geometry_msgs.msg.Vector3()
      if self.speed_accuracy_estimate is None:
        self.speed_accuracy_estimate = 0.
      if self.error_present is None:
        self.error_present = False
      if self.error_string is None:
        self.error_string = ''
    else:
      self.header = std_msgs.msg.Header()
      self.latitude = 0.
      self.longitude = 0.
      self.altitude = 0.
      self.num_satellites = 0
      self.ned_velocities = geometry_msgs.msg.Vector3()
      self.ned_acceleration = geometry_msgs.msg.Vector3()
      self.speed_accuracy_estimate = 0.
      self.error_present = False
      self.error_string = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3di7dB.pack(_x.latitude, _x.longitude, _x.altitude, _x.num_satellites, _x.ned_velocities.x, _x.ned_velocities.y, _x.ned_velocities.z, _x.ned_acceleration.x, _x.ned_acceleration.y, _x.ned_acceleration.z, _x.speed_accuracy_estimate, _x.error_present))
      _x = self.error_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ned_velocities is None:
        self.ned_velocities = geometry_msgs.msg.Vector3()
      if self.ned_acceleration is None:
        self.ned_acceleration = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 85
      (_x.latitude, _x.longitude, _x.altitude, _x.num_satellites, _x.ned_velocities.x, _x.ned_velocities.y, _x.ned_velocities.z, _x.ned_acceleration.x, _x.ned_acceleration.y, _x.ned_acceleration.z, _x.speed_accuracy_estimate, _x.error_present,) = _struct_3di7dB.unpack(str[start:end])
      self.error_present = bool(self.error_present)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.error_string = str[start:end].decode('utf-8')
      else:
        self.error_string = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3di7dB.pack(_x.latitude, _x.longitude, _x.altitude, _x.num_satellites, _x.ned_velocities.x, _x.ned_velocities.y, _x.ned_velocities.z, _x.ned_acceleration.x, _x.ned_acceleration.y, _x.ned_acceleration.z, _x.speed_accuracy_estimate, _x.error_present))
      _x = self.error_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ned_velocities is None:
        self.ned_velocities = geometry_msgs.msg.Vector3()
      if self.ned_acceleration is None:
        self.ned_acceleration = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 85
      (_x.latitude, _x.longitude, _x.altitude, _x.num_satellites, _x.ned_velocities.x, _x.ned_velocities.y, _x.ned_velocities.z, _x.ned_acceleration.x, _x.ned_acceleration.y, _x.ned_acceleration.z, _x.speed_accuracy_estimate, _x.error_present,) = _struct_3di7dB.unpack(str[start:end])
      self.error_present = bool(self.error_present)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.error_string = str[start:end].decode('utf-8')
      else:
        self.error_string = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_3di7dB = struct.Struct("<3di7dB")
