TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  #max_vel_y: 0.0
  max_vel_theta: 1.5
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 1.5
  acc_lim_x: 0.5
  acc_lim_y: 0.0


  holonomic_robot: false

  vx_sample: 20
  vy_sample: 0.0
  vtheta_samples: 40

  #path_distance_bias: 32.0
  #goal_distance_bias: 20.0

  pdist_scale: 5.0
  gdist_scale: 0.2
  occdist_scale: 0.02
